[package]
name = "graphql-ws-client"
version = "0.1.0"
authors = ["Graeme Coupar <graeme@polyandglot.dev>"]
edition = "2018"
description = "A graphql over websockets client"
license = "Apache-2.0"
autoexamples = false

[workspace]
members = ["examples"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["async-tungstenite", "ws_stream_wasm", "cynic"]

[dependencies]
async_executors = { version = "0.4.2" }
futures = { version = "0.3" }
pin-project = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
uuid = { version = "0.8", features = ["v4"] }

async-tungstenite = { version = "0.13", optional = true }
ws_stream_wasm = { version = "0.7", optional = true }

cynic = { version = "0.14", optional = true }
log = "*"

[dev-dependencies]
insta = "1.7"
