[package]
name = "examples"
version = "0.1.0"
authors = ["Graeme Coupar <grambo@grambo.me.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql-ws-client = { path = "../", features = ["cynic", "async-tungstenite"] }

async-std = { version = "1.9", features = ["attributes"] }
async-tungstenite = { version = "0.13", features = ["async-std-runtime"] }
async_executors = { version = "0.4", features = ["async_std"] }
cynic = { version = "0.13" }
futures = { version = "0.3"}

[dev-dependencies]
insta = "1.7"